### ISSUE TITLE
logging to syslog stopped working in 1.7.2

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#134]
After the upgrade to 1.7.2 logging to syslog does not work anymore.

**Comment by andris9** [comment]
This is intentional, I needed to remove compiled dependencies and node syslog requires native bindings. Instead the correct way to run ZoneMTA would be to run it as a systemd service and use SyslogIdentifier and SyslogFacility properties to describe it. See example usage [here](https://github.com/zone-eu/zone-mta/blob/master/setup/zone-mta.service)
