### ISSUE TITLE
lmtp delivery example

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#192]
Is there any lmtp delivery plugin example ?
How does lmtp delivery work ? Are lmtp errors passed to the smtp incoming connection ?

**Comment by andris9** [comment]
Using LMTP should be quite transparent. Delivery errors from LMTP server are treated the same way as errors from normal SMTP MX servers. If LMTP is enabled then ZoneMTA uses LMTP protocol instead of SMTP. In most cases it is exactly the same, the main difference being that LMTP server responds with either a success or failure response for each of the recipients after DATA (SMTP servers responds a single response applies to all recipients). As ZoneMTA delivers all emails one by one, then the difference between LMTP and SMTP does not apply.

You can enable LMTP for a message by using a plugin as it is not enabled by default:

```javascript
app.addHook('sender:fetch', (delivery, next) => {
    delivery.useLMTP = true;
    next();
});
```
