### ISSUE TITLE
Suggestion for cloud platform to host zonemta

### ISSUE THREAD

**Issue by alash3al** [zone-eu/zone-mta#199]
Hello,

At first sorry for posting this question here,

I just want to know the best cloud platforms to host zone MTA, with no issues, as there are some platforms that restrict any email based actions.

**Comment by ppadron** [comment]
I'm not sure about cloud servers, but I was a happy customer of Online.net/Scaleway with their dedicated servers and now I'm at OVH (Canada DC).

If you try Scaleway, port 25 is blocked by default, but you can change that in their control panel.

**Comment by dazoot** [comment]
Hetzner is good too.

**Comment by andris9** [comment]
You can run ZoneMta on any cloud platform that does not block port 25. Some never open it, some open it once you have been a paying customer for a while or submit a request. Large cloud platforms that do not filter port 25 usage at all usually have their IP ranges in different blacklists (because it is very easy to start spamming), so do your research first. Smaller providers (even though usually more expensive) might provide a good opportunity - as they have fewer clients and higher prices then their IPs might be cleaner as well.
