### ISSUE TITLE
message:headers plugin issue with reject bigger messages

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#205]
I have a small plugin which checks if there is a X-Spam header in the message and if yes it returns an error.

If the message is small i get to see the SMTP error.
If the message is bigger (~1mb) the SMTP session hangs. I get a timeout in my smtp client.

If i change the hook to `message:queue` i get to see the ERROR in the SMTP client.

plugin code:
```javascript
    app.addHook('message:headers', (envelope, messageInfo, next) => {
        if (envelope.headers.getFirst("x-spam") || envelope.headers.getFirst("x-spam-flag"))
        {
                let err = new Error('Message NOT sent to ' + envelope.to + ', because it was detected as SPAM. Subject = ' + envelope.headers.getFirst("subject"));
                err.responseCode = 554;
                // delivery.skipBounce = err.message;
                return next(err);
        }
        next();
    });
```

Is this normal ?
What is the difference between `message:headers` and `message:queue` ?

**Comment by andris9** [comment]
'message:headers' happens when header part is already written to SMTP by the client. This step should be treater more like informational, you can do some header rewriting or routing decisions at this point. To actually reject it you should wait until 'message:queue' which happens when server starts writing message info to queue database.
