### ISSUE TITLE
DANE / MTA-STS support

### ISSUE THREAD

**Issue by Stefan-ST** [zone-eu/zone-mta#253]
Are there plans to support DANE and/or MTA-STS?

Google already supports MTA-STS and Microsoft has announced support for DANE.

**Comment by andris9** [comment]
MTA-STS is planned, no ETA though. DANE is not planned, mostly because Node.js does not natively support resolving TLSA records.

**Comment by andris9** [comment]
Once resolveTsla is in Node LTS, then we could consider it. In general DANE support has 0 priority, I see no value at all in it. MTA-STS is already supported.

**Comment by louis-lau** [comment]
I would like to see it at one point as well, as MTA-STS seems to have been superseded by DANE in the eyes of some, which I don't really agree with tbh. But especially because there's no preload list (https://www.eff.org/deeplinks/2020/04/winding-down-starttls-everywhere-project-and-future-secure-email), DANE is a lot more secure.

So I could see a future where recipients implement DANE and not MTA-STS, so the need to check both would be there. And if someone does both, DANE will be more secure and MTA-STS more like a fallback.

But yeah, it's not possible until it's in node LTS at the very least, and if implemented then it would force a version update for everyone. Might not be a problem, but worth thinking about :). Always need to have a lot of patience watching for progress in the world of email haha

**Comment by andris9** [comment]
Well, yeah, once TLSA is available in Node LTS then there is no reason not to support DANE anymore.

**Comment by titanism** [comment]
This belongs in `mx-connect`, not in this project.  Will open a PR there.
