### ISSUE TITLE
Incorrect classification in bounce rules

### ISSUE THREAD

**Issue by roshanjonah** [zone-eu/zone-mta#324]
Is there a way to change the bounce rules or add a certain rule via a custom plugin? 

Currently, we have an "other" category setup as soft fails and a mail server that returns 550 No user found is also being classified as a soft fail. It should be classified as a hard bounce.

A possible rule being applied from bounce.txt 
![image_2023_03_09T09_04_05_550Z](https://user-images.githubusercontent.com/20136098/224568680-78d4ee91-88af-41e1-b469-139f7a098873.png)

How we see it coming in
![CleanShot 2023-03-13 at 08 29 50@2x](https://user-images.githubusercontent.com/20136098/224568696-bd8e76c8-2550-4668-936c-f11de1bdb3c2.png)

We can't really change it from soft to hard because most other reasons in that "other" category are actually soft failures. This is the odd one out. Recommendations? Thoughts anyone?

**Comment by louis-lau** [comment]
I feel like detecting a soft/hard bounce based on the error category in bounces.txt is the wrong approach anyway. But if you want then yes, you can edit bounces.txt. I don't think there's anything stopping you.

> How we see it coming in

How are you getting the bounce data?

**Comment by louis-lau** [comment]
If I were you I would submit a PR to zone-mta, so that it also passes along the action and not just the category.
Pretty sure you should be able to add `bounce.action` to this object here:
https://github.com/zone-eu/zone-mta/blob/b22909e23ec6fb31815a5aa550c9101c565ab199/lib/sender.js#L1477-L1498

Should also be useful to others, so I see no reason such a PR wouldn't be accepted. I'm not a maintainer on this project though.
