### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by w3update** [zone-eu/zone-mta#75]
This is great app.

It is most complete open source MTA which has enterprise level of features.

**You can consider some core features for future release:**
Automatic discard email based non-mx record
Discard bad emails from auto retry(hard bounce and add into suppression list).
Suppression list at MTA level (list of bad email ids which would not receive any future emails)
Retain Logs i.e. Delivered, Bounces etc. in Mongodb for further export.

Thanks

**Comment by andris9** [comment]
Thanks!

**Automatic discard email based non-mx record**

There are a lot of servers without MX records but valid A record with the SMTP server listening on port 25 of the A record and accepting mail. This is also what the spec requires.

**Discard bad emails from auto retry**

It's hard to tell which emails are bad and which are not. ZoneMTA used to be stricter on this but we had a lot of trouble sending emails to China, because of long delays. DNS queries sometimes failed, network was unstable etc. Unless there is not a clear 5XX response from the server then it is no easy way to tell if the email is bad or not. For us it seemed easier to have a few thousand bad emails sitting in the deferred queue than hard bouncing messages that might eventually get through.

**Suppression list at MTA level**

Sounds reasonable.

**Retain Logs i.e. Delivered, Bounces etc. in Mongodb for further export**

This is currently in works as I want to get rid of the LevelDB and move queue handling also to MongoDB.

**Comment by andris9** [comment]
**Automatic discard email based non-mx record**

The version in master branch discards messages without MX records after first attempt. If a connection can not be established against the A record, then message is rejected

**Suppression list at MTA level**

This is done. Addresses and domains listed in suppression list are silently dropped. ZMTA-WebAdmin has a new section "Suppression list" for managing the list.

**Retain Logs i.e. Delivered, Bounces etc. in Mongodb for further export**

Logs are not automatically stored. ZoneMTA emits logs over UDP, so you can create your own logging agent that stores these logs. See the example for setting up such logging agent here: https://gist.github.com/andris9/f96298d181ffd524a7d52de375c7c660
